services:
  paddlex-server:
    image: paddlex/app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paddlex-server
    environment:
      - PADDLEX_HPS_DEVICE_TYPE=gpu
      - IMAGE_CAPTIONING_ENABLED=${IMAGE_CAPTIONING_ENABLED:-true}
    volumes:
      # Mount .env file for environment variables
      - ./.env:/app/.env
      # Mount paddlex models directory (excluded from image)
      # - ./paddlex:/app/paddlex:ro
      - ./paddlex/official_models:/root/.paddlex/official_models
      # Only mount specific config file if needed to override
      # - ./config_gpu_paddlex.pbtxt:/app/server/model_repo/layout-parsing/config_gpu.pbtxt
    ports:
      - "8000:8000"            # Triton HTTP endpoint
      - "8001:8001"            # Triton gRPC endpoint
      - "8002:8002"            # Triton metrics endpoint
      - "8081:8081"            # Instance status endpoint
    shm_size: 8g
    init: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - xyne

  blip-server:
    image: paddlex/app:latest
    container_name: blip-server
    profiles:
      - image-captioning
    volumes:
      - ./config_gpu_blip.pbtxt:/app/server/model_repo/blip-caption/config_gpu.pbtxt
      # Mount BLIP model cache directory (excluded from image)
      # - ./server/model_repo/blip-caption/1/blip_model_cache:/app/server/model_repo/blip-caption/1/blip_model_cache
    working_dir: /app/server
    command: |
      bash -lc '
      cp model_repo/blip-caption/config_gpu.pbtxt model_repo/blip-caption/config.pbtxt && 
      tritonserver --model-repository=model_repo --model-control-mode=explicit --load-model=blip-caption --grpc-port=8004 --http-port=8003 --metrics-port=8005 --log-info=1 --log-warning=1 --log-error=1
      '
    ports:
      - "8003:8003"  # BLIP HTTP
      - "8004:8004"  # BLIP gRPC
      - "8005:8005"  # BLIP metrics endpoint
    shm_size: 1g
    init: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - xyne

networks:
  xyne:
    external: true
